In [1]:
import numpy as np

In [22]:
a = np.array([0.])
b = a/a * (1/a)
b[0]


C:\Users\ljb\Anaconda2\envs\simplyp\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in divide
  
C:\Users\ljb\Anaconda2\envs\simplyp\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in divide
  


nan

In [26]:
np.nan_to_num(1./a)

C:\Users\ljb\Anaconda2\envs\simplyp\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([1.79769313e+308])

In [28]:
np.nan_to_num(a/a * 1./a)

C:\Users\ljb\Anaconda2\envs\simplyp\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in divide
  """Entry point for launching an IPython kernel.


array([0.])

In [15]:
a/a

C:\Users\ljb\Anaconda2\envs\simplyp\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0])